/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_jna_win32_DLLCallback */

#ifndef _Included_com_sun_jna_win32_DLLCallback
#define _Included_com_sun_jna_win32_DLLCallback
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sun_jna_win32_DLLCallback_DLL_FPTRS
#define com_sun_jna_win32_DLLCallback_DLL_FPTRS 16L
#ifdef __cplusplus
}
#endif
#endif
