#!/bin/sh

function cleanup() {
  if test -d "$1"; then
    prev=$(pwd)
    cd "$1"
    if test "$1" != "." && test -f cleanup; then
      prev_backup=$prev
      . cleanup
      prev=$prev_backup
    else
      rm -f Makefile
      rm -f Makefile.in
      rm -f aclocal.m4
      rm -f config.*
      rm -f configure
      rm -f depcomp
      rm -f install-sh
      rm -f ltmain.sh
      rm -f makefiles.*~
      rm -f mdate-sh
      rm -f missing
      rm -f libtool
      rm -f stamp-h1
      rm -f *.o *.a *.la *.lo *.obj *.lib *.exe *.dll
      rm -fR autom4te.cache
      rm -fR .deps
      rm -fR .libs
    fi
    cd $prev
  fi
}

function cleanup_libltdl() {
  if test -d libltdl; then
    cleanup libltdl
    cd libltdl
    rm -f config/compile
    rm -f config/config.guess
    rm -f config/config.sub
    rm -f config/depcomp
    rm -f config/install-sh
    rm -f config/missing
    rm -f config/ltmain.sh
    rm -f m4/argz.m4
    rm -f m4/libtool.m4
    rm -f m4/ltdl.m4
    rm -f m4/ltoptions.m4
    rm -f m4/ltsugar.m4
    rm -f m4/ltversion.m4
    rm -f m4/lt~obsolete.m4
    rm -f COPYING.LIB
    rm -f README
    rm -f Makefile.am
    rm -f configure.ac
    rm -f aclocal.m4
    rm -f Makefile.in
    rm -f config-h.in
    rm -f configure
    rm -f argz_.h
    rm -f argz.c
    rm -f argz.h
    rm -f loaders/dld_link.c
    rm -f loaders/dlopen.c
    rm -f loaders/dyld.c
    rm -f loaders/load_add_on.c
    rm -f loaders/loadlibrary.c
    rm -f loaders/shl_load.c
    rm -f lt__dirent.c
    rm -f lt__strl.c
    rm -f libltdl/lt__alloc.h
    rm -f libltdl/lt__dirent.h
    rm -f libltdl/lt__glibc.h
    rm -f libltdl/lt__private.h
    rm -f libltdl/lt__strl.h
    rm -f libltdl/lt_dlloader.h
    rm -f libltdl/lt_error.h
    rm -f libltdl/lt_system.h
    rm -f libltdl/slist.h
    rm -f loaders/preopen.c
    rm -f lt__alloc.c
    rm -f lt_dlloader.c
    rm -f lt_error.c
    rm -f ltdl.c
    rm -f ltdl.h
    rm -f slist.c
    cd ..
  fi
}

cleanup .
cleanup include
cleanup libraries
cleanup main
cleanup_libltdl
