/* confdefs.h */
#define PACKAGE_NAME "jnidispatch"
#define PACKAGE_TARNAME "jnidispatch"
#define PACKAGE_VERSION "1.11"
#define PACKAGE_STRING "jnidispatch 1.11"
#define PACKAGE_BUGREPORT "berryzplus@gmail.com"
#define PACKAGE_URL ""
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define LT_OBJDIR ".libs/"
#define LT_MODULE_EXT ".dll"
#define LT_MODULE_PATH_VAR "PATH"
#define LT_DLSEARCH_PATH "/lib:/usr/lib"
#define HAVE_DECL_CYGWIN_CONV_PATH 0
#define HAVE_LIBDLLOADER 1
#define LTDL_DLOPEN_DEPLIBS 1
#define error_t int
#define __error_t_defined 1
#define HAVE_PRELOADED_SYMBOLS 1
#define LT_LIBEXT "lib"
#define LT_LIBPREFIX ""
#define PACKAGE "jnidispatch"
#define VERSION "1.11"
#define HAVE_ALLOCA 1
#define HAVE_MALLOC_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_WCHAR_H 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define HAVE_MEMSET 1
