/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_jna_Native_ffi_callback */

#ifndef _Included_com_sun_jna_Native_ffi_callback
#define _Included_com_sun_jna_Native_ffi_callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
