/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_jna_Function_PointerArray */

#ifndef _Included_com_sun_jna_Function_PointerArray
#define _Included_com_sun_jna_Function_PointerArray
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
