/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_jna_Native_Buffers */

#ifndef _Included_com_sun_jna_Native_Buffers
#define _Included_com_sun_jna_Native_Buffers
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
