/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_jna_Function_PostCallRead */

#ifndef _Included_com_sun_jna_Function_PostCallRead
#define _Included_com_sun_jna_Function_PostCallRead
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
